new27

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -6,7 +6,7 @@ env:
     FRONTEND_BUCKET: "yourfrontendbucketfilesharingmetadataservice"
     LAMBDA_FUNCTION_NAME: "uploadmetadat"
     ECS_CONTAINER_NAME: "fileshare"
-    DB_HOST: "metadatadb.claw0qi2e.ap-south-1.rds.amazonaws.com"
+    DB_HOST: "metadatadb.claw0qi2ez2e.ap-south-1.rds.amazonaws.com"
     DB_NAME: "metadatadb"
     DB_PORT: "3306"
     SECRET_NAME: "metadata/"
@@ -31,10 +31,10 @@ phases:
       - echo "Retrieving DB credentials from Secrets Manager..."
       - export DB_USER=$(aws secretsmanager get-secret-value --secret-id my-db-secret --query SecretString --output text | jq -r '.username')
       - export DB_PASS=$(aws secretsmanager get-secret-value --secret-id my-db-secret --query SecretString --output text | jq -r '.password')
-      
-      - echo "Logging in to Amazon ECR..."
-      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
-      - aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPO_URI%%/*}
+      - |
+        IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
+        IMAGE_PREFIX=${ECR_REPO_URI%%/*}
+        aws ecr get-login-password | docker login --username AWS --password-stdin $IMAGE_PREFIX
 
   build:
     commands:
@@ -60,13 +60,16 @@ phases:
       
       - echo "Checking if schema.sql file is present..."
       - ls -l ./sql/schema.sql || echo "Warning: schema.sql not found, skipping DB schema load."
-
-      - |
-        if [ -f ./sql/schema.sql ]; then
-          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p"$DB_PASS" $DB_NAME < ./sql/schema.sql || echo "Warning: Failed to run schema.sql";
-        else
-          echo "No schema.sql found, skipping.";
-        fi
+      
+      # Uncomment below if you want to test MySQL connectivity and run schema.sql
+      # - echo "Testing MySQL connectivity..."
+      # - mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p"$DB_PASS" -e "SHOW DATABASES;" || echo "Warning: Cannot connect to MySQL, skipping schema load."
+      
+      # - if [ -f ./sql/schema.sql ]; then
+      #     mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p"$DB_PASS" $DB_NAME < ./sql/schema.sql || echo "Warning: Failed to run schema.sql";
+      #   else
+      #     echo "No schema.sql found, skipping.";
+      #   fi
 
 artifacts:
   files:
